org.gradle.jvmargs=-Xmx8G

# Project Versions
java_version=21
mixin_version=0.8.4
fabric_loom_version=1.10-SNAPSHOT
mod_dev_gradle_version=2.0.80
mod_publish_plugin_version=0.8.4

# Build Jar
minecraft_version=1.21.1
minimum_minecraft_version=1.21.1

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
neo_form_version=1.21.1-20240808.144430

# Mod Information

# Changing the mod_id alone will not change it everywhere. There will have to be some manual edits in each loader files in order to change mod id fully
mod_id=templatemod

mod_name=Template Mod
mod_version=1.0.0
mod_release_type=Release
mod_base_package=mc.mian.templatemod
mod_authors=MianReplicate
mod_description=I am a template woooo
mod_credits=Jeryn99 (Code), Tanger (Sounds)
mod_license=PolyForm Shield License 1.0.0
logo_file=logo.png
repository_url=https://github.com/MianReplicate/TemplateMod
issue_tracker_url=https://github.com/MianReplicate/TemplateMod/issues

# For publishing purposes
curseforge_id=811168
modrinth_id=olO9KLa1

# Common dependencies
common_networking_version=1.0.18-1.21.1
mixin_extras_version=0.4.1
forge_config_api_port_version=21.1.3

# NeoForge dependencies
neo_version=21.1.139
neo_version_range=[21,)
neo_loader_version_range=[1,)

# Forge dependencies
forge_version=52.1.0
forge_version_range=[52,)
forge_loader_version_range=[52,)

# Fabric dependencies
fabric_loader_version=0.16.3
fabric_api_version=0.115.3